/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicDownloadRouteImport } from './routes/_public/download'
import { Route as PublicRedirectRouteImport } from './routes/_public/redirect'
import { Route as StaffStaffRouteImport } from './routes/staff/_staff'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffStaffGameContributionsRouteImport } from './routes/staff/_staff/game-contributions'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDownloadRoute = PublicDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRedirectRoute = PublicRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => PublicRoute,
} as any)
const StaffStaffRoute = StaffStaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffGameContributionsRoute =
  StaffStaffGameContributionsRouteImport.update({
    id: '/game-contributions',
    path: '/game-contributions',
    getParentRoute: () => StaffStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/staff': typeof StaffRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/download': typeof PublicDownloadRoute
  '/redirect': typeof PublicRedirectRoute
  '/staff/login': typeof StaffLoginRoute
  '/staff/game-contributions': typeof StaffStaffGameContributionsRoute
}
export interface FileRoutesByTo {
  '/staff': typeof StaffRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/download': typeof PublicDownloadRoute
  '/redirect': typeof PublicRedirectRoute
  '/staff/login': typeof StaffLoginRoute
  '/': typeof PublicIndexRoute
  '/staff/game-contributions': typeof StaffStaffGameContributionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/download': typeof PublicDownloadRoute
  '/_public/redirect': typeof PublicRedirectRoute
  '/staff/_staff': typeof StaffStaffRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/staff/_staff/game-contributions': typeof StaffStaffGameContributionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/staff'
    | '/about'
    | '/download'
    | '/redirect'
    | '/staff/login'
    | '/staff/game-contributions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/staff'
    | '/about'
    | '/download'
    | '/redirect'
    | '/staff/login'
    | '/'
    | '/staff/game-contributions'
  id:
    | '__root__'
    | '/_public'
    | '/staff'
    | '/_public/about'
    | '/_public/download'
    | '/_public/redirect'
    | '/staff/_staff'
    | '/staff/login'
    | '/_public/'
    | '/staff/_staff/game-contributions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/download': {
      id: '/_public/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof PublicDownloadRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/redirect': {
      id: '/_public/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof PublicRedirectRouteImport
      parentRoute: typeof PublicRoute
    }
    '/staff/_staff': {
      id: '/staff/_staff'
      path: ''
      fullPath: '/staff'
      preLoaderRoute: typeof StaffStaffRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/_staff/game-contributions': {
      id: '/staff/_staff/game-contributions'
      path: '/game-contributions'
      fullPath: '/staff/game-contributions'
      preLoaderRoute: typeof StaffStaffGameContributionsRouteImport
      parentRoute: typeof StaffStaffRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicDownloadRoute: typeof PublicDownloadRoute
  PublicRedirectRoute: typeof PublicRedirectRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicDownloadRoute: PublicDownloadRoute,
  PublicRedirectRoute: PublicRedirectRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface StaffStaffRouteChildren {
  StaffStaffGameContributionsRoute: typeof StaffStaffGameContributionsRoute
}

const StaffStaffRouteChildren: StaffStaffRouteChildren = {
  StaffStaffGameContributionsRoute: StaffStaffGameContributionsRoute,
}

const StaffStaffRouteWithChildren = StaffStaffRoute._addFileChildren(
  StaffStaffRouteChildren,
)

interface StaffRouteChildren {
  StaffStaffRoute: typeof StaffStaffRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffRoute: StaffStaffRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
