/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconFa6SolidCrow: typeof import('~icons/fa6-solid/crow.jsx')['default']
  const IconGravityUiPlus: typeof import('~icons/gravity-ui/plus.jsx')['default']
  const IconLineMdAlert: typeof import('~icons/line-md/alert.jsx')['default']
  const IconMdiCamera: typeof import('~icons/mdi/camera.jsx')['default']
  const IconMdiClose: typeof import('~icons/mdi/close.jsx')['default']
  const IconMdiHide: typeof import('~icons/mdi/hide.jsx')['default']
  const IconMdiIdentificationCard: typeof import('~icons/mdi/identification-card.jsx')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout.jsx')['default']
  const IconMdiMaximize: typeof import('~icons/mdi/maximize.jsx')['default']
  const IconMdiMinimize: typeof import('~icons/mdi/minimize.jsx')['default']
  const IconMdiNotifications: typeof import('~icons/mdi/notifications.jsx')['default']
  const IconMdiServer: typeof import('~icons/mdi/server.jsx')['default']
  const IconMdiSettings: typeof import('~icons/mdi/settings.jsx')['default']
  const IconMdiShow: typeof import('~icons/mdi/show.jsx')['default']
  const IconMdiSpeakerphone: typeof import('~icons/mdi/speakerphone.jsx')['default']
  const IconSvgSpinners3DotsFade: typeof import('~icons/svg-spinners/3-dots-fade.jsx')['default']
}
