/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMdiCamera: typeof import('~icons/mdi/camera.jsx')['default']
  const IconMdiHide: typeof import('~icons/mdi/hide.jsx')['default']
  const IconMdiShow: typeof import('~icons/mdi/show.jsx')['default']
  const IconSvgSpinners3DotsFade: typeof import('~icons/svg-spinners/3-dots-fade.jsx')['default']
}
