# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM debian AS base
LABEL org.opencontainers.image.source=https://github.com/werdoxdev/huginn
WORKDIR /src

RUN apt update && apt install -y curl python3 python3-pip unzip && rm -rf /var/lib/apt/lists/*
RUN curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && apt install -y nodejs
RUN curl -fsSL https://bun.sh/install | bash -s "bun-v1.3.5"
ENV PATH="/usr/local/bin:$PATH"
ENV PATH="/root/.bun/bin:$PATH"
RUN bun -v && node -v && npm -v && python3 --version && pip3 --version

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/deps
COPY package.json bun.lock bunfig.toml .npmrc /temp/deps/
COPY packages/huginn-backend-shared/package.json /temp/deps/packages/huginn-backend-shared/package.json
COPY packages/huginn-runtime-shared/package.json /temp/deps/packages/huginn-runtime-shared/package.json
COPY packages/huginn-shared/package.json /temp/deps/packages/huginn-shared/package.json
COPY packages/huginn-voice/package.json /temp/deps/packages/huginn-voice/package.json
RUN cd /temp/deps && bun install

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/deps/node_modules node_modules
# COPY --from=install /temp/deps/packages/huginn-backend-shared/node_modules packages/huginn-backend-shared/node_modules
# COPY --from=install /temp/deps/packages/huginn-shared/node_modules packages/huginn-shared/node_modules
# COPY --from=install /temp/deps/packages/huginn-voice/node_modules packages/huginn-voice/node_modules
COPY . /src
RUN cd packages/huginn-backend-shared && bunx prisma generate
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# run the app
# RUN mkdir -p packages/huginn-cdn/uploads
# RUN chown -R bun:bun packages/huginn-cdn/uploads
# RUN chown -R bun:bun packages/huginn-server/package.json
# RUN chmod 755 packages/huginn-cdn/uploads
# RUN chmod 755 packages/huginn-server/package.json
# USER bun
EXPOSE 3003/tcp
EXPOSE 44444/tcp
ENTRYPOINT ["/entrypoint.sh"]
CMD ["packages/huginn-voice", "voice", "npm"]
