FROM caddy:builder AS builder
LABEL org.opencontainers.image.source=https://github.com/werdoxdev/huginn

RUN xcaddy build --with github.com/mholt/caddy-l4

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
