version: "3.8"

networks:
   caddy:
      external: true

services:
   caddy:
      image: ghcr.io/werdoxdev/caddy:latest
      configs:
         - source: caddy_config
           target: /etc/caddy/Caddyfile
      networks:
         - caddy
      deploy:
         restart_policy:
            condition: on-failure

   server:
      image: ghcr.io/werdoxdev/huginn-server:latest
      environment:
         - SERVER_HOST=0.0.0.0
         - SERVER_PORT=3004
         - ALLOWED_ORIGINS=http://localhost:5173/,https://app.huginn.dev/,https://dev.huginn.dev/,https://huginn.dev
         - CDN_LOCAL_URL=http://cdn:3002/cdn
      secrets:
         - backend_secrets
      networks:
         - caddy
      volumes:
         - type: bind
           source: /var/lib/huginn-logs
           target: /src/packages/huginn-server/logs
      deploy:
         resources:
            limits:
               memory: 2g
               cpus: "2.0"
         restart_policy:
            condition: on-failure
            delay: 5s

   cdn:
      image: ghcr.io/werdoxdev/huginn-cdn:latest
      environment:
         - CDN_HOST=0.0.0.0
         - CDN_PORT=3002
      secrets:
         - backend_secrets
      networks:
         - caddy
      deploy:
         resources:
            limits:
               memory: 2g
               cpus: "2.0"
         restart_policy:
            condition: on-failure
            delay: 5s

   voice:
      image: ghcr.io/werdoxdev/huginn-voice:latest
      environment:
         - VOICE_HOST=0.0.0.0
         - VOICE_PORT=3003
         - MEDIA_LISTEN_INFOS=udp:44443:0.0.0.0:monolith.werdox.com;udp:44444:0.0.0.0:midgard.huginn.dev
      ports:
         - target: 44444
           published: 44444
           protocol: udp
           mode: host
         - target: 44443
           published: 44443
           protocol: udp
           mode: host
         - target: 44444
           published: 44444
           protocol: tcp
           mode: host
      secrets:
         - backend_secrets
      networks:
         - caddy
      deploy:
         resources:
            limits:
               memory: 2g
               cpus: "2.0"
         restart_policy:
            condition: on-failure
            delay: 5s

configs:
   caddy_config:
      external: true

secrets:
   backend_secrets:
      external: true
