FROM node:24-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN corepack enable
WORKDIR /src

RUN apk add --no-cache curl python3 py3-pip unzip g++ linux-headers
RUN node -v && pnpm -v && python3 --version && pip3 --version

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/deps

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc /temp/deps/
COPY packages/huginn-backend-shared/package.json /temp/deps/packages/huginn-backend-shared/package.json
COPY packages/huginn-runtime-shared/package.json /temp/deps/packages/huginn-runtime-shared/package.json
COPY packages/huginn-shared/package.json /temp/deps/packages/huginn-shared/package.json
COPY packages/huginn-voice/package.json /temp/deps/packages/huginn-voice/package.json

RUN cd /temp/deps && pnpm install --frozen-lockfile

FROM oven/bun:1.4.0-alpine AS prerelease
LABEL org.opencontainers.image.source=https://github.com/werdoxdev/huginn
WORKDIR /src

COPY . /src
COPY --from=install /temp/deps/node_modules node_modules
COPY --from=install /temp/deps/packages/huginn-backend-shared/node_modules packages/huginn-backend-shared/node_modules
COPY --from=install /temp/deps/packages/huginn-runtime-shared/node_modules packages/huginn-runtime-shared/node_modules
COPY --from=install /temp/deps/packages/huginn-shared/node_modules packages/huginn-shared/node_modules
COPY --from=install /temp/deps/packages/huginn-voice/node_modules packages/huginn-voice/node_modules

RUN cd packages/huginn-backend-shared && bunx prisma generate
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3003/tcp
EXPOSE 44444/tcp
ENTRYPOINT ["/entrypoint.sh"]
CMD ["packages/huginn-voice", "voice"]
