/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconBiGithub: typeof import('~icons/bi/github.jsx').default
  const IconEosIconsApi: typeof import('~icons/eos-icons/api.jsx').default
  const IconIcBaselineDiscord: typeof import('~icons/ic/baseline-discord.jsx').default
  const IconMaterialSymbolsBrush: typeof import('~icons/material-symbols/brush.jsx').default
  const IconMaterialSymbolsMenu: typeof import('~icons/material-symbols/menu.jsx').default
  const IconMdiClose: typeof import('~icons/mdi/close.jsx').default
  const IconMdiTwitter: typeof import('~icons/mdi/twitter.jsx').default
  const IconMdiX: typeof import('~icons/mdi/x.jsx').default
  const IconMingcuteAndroidFill: typeof import('~icons/mingcute/android-fill.jsx').default
  const IconMingcuteAppleFill: typeof import('~icons/mingcute/apple-fill.jsx').default
  const IconMingcuteArrowDownFill: typeof import('~icons/mingcute/arrow-down-fill.jsx').default
  const IconMingcuteCancelFill: typeof import('~icons/mingcute/cancel-fill.jsx').default
  const IconMingcuteCheckCircleFill: typeof import('~icons/mingcute/check-circle-fill.jsx').default
  const IconMingcuteChromeFill: typeof import('~icons/mingcute/chrome-fill.jsx').default
  const IconMingcuteCloseFill: typeof import('~icons/mingcute/close-fill.jsx').default
  const IconMingcuteDownFill: typeof import('~icons/mingcute/down-fill.jsx').default
  const IconMingcuteDownload3Fill: typeof import('~icons/mingcute/download3-fill.jsx').default
  const IconMingcuteExitFill: typeof import('~icons/mingcute/exit-fill.jsx').default
  const IconMingcuteGame2Fill: typeof import('~icons/mingcute/game2-fill.jsx').default
  const IconMingcuteGroup3Fill: typeof import('~icons/mingcute/group3-fill.jsx').default
  const IconMingcuteLightningFill: typeof import('~icons/mingcute/lightning-fill.jsx').default
  const IconMingcuteLinuxFill: typeof import('~icons/mingcute/linux-fill.jsx').default
  const IconMingcutePaint2Fill: typeof import('~icons/mingcute/paint2-fill.jsx').default
  const IconMingcutePicFill: typeof import('~icons/mingcute/pic-fill.jsx').default
  const IconMingcuteRefresh2Fill: typeof import('~icons/mingcute/refresh2-fill.jsx').default
  const IconMingcuteSearch2Fill: typeof import('~icons/mingcute/search2-fill.jsx').default
  const IconMingcuteWindowsFill: typeof import('~icons/mingcute/windows-fill.jsx').default
  const IconRaphaelOpensource: typeof import('~icons/raphael/opensource.jsx').default
  const IconRiInstagramFill: typeof import('~icons/ri/instagram-fill.jsx').default
  const IconRiShieldKeyholeFill: typeof import('~icons/ri/shield-keyhole-fill.jsx').default
  const IconSvgSpinnersRingResize: typeof import('~icons/svg-spinners/ring-resize.jsx').default
}
