/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLetsIconsSendHorFill: typeof import('~icons/lets-icons/send-hor-fill.jsx')['default']
  const IconLogosGithubIcon: typeof import('~icons/logos/github-icon.jsx')['default']
  const IconLogosGoogleIcon: typeof import('~icons/logos/google-icon.jsx')['default']
  const IconMingcuteAddFill: typeof import('~icons/mingcute/add-fill.jsx')['default']
  const IconMingcuteAlertFill: typeof import('~icons/mingcute/alert-fill.jsx')['default']
  const IconMingcuteAlertLine: typeof import('~icons/mingcute/alert-line.jsx')['default']
  const IconMingcuteArrowLeftFill: typeof import('~icons/mingcute/arrow-left-fill.jsx')['default']
  const IconMingcuteArrowRightFill: typeof import('~icons/mingcute/arrow-right-fill.jsx')['default']
  const IconMingcuteCheckFill: typeof import('~icons/mingcute/check-fill.jsx')['default']
  const IconMingcuteCloseFill: typeof import('~icons/mingcute/close-fill.jsx')['default']
  const IconMingcuteCopy2Fill: typeof import('~icons/mingcute/copy2-fill.jsx')['default']
  const IconMingcuteDelete2Fill: typeof import('~icons/mingcute/delete2-fill.jsx')['default']
  const IconMingcuteDelete3Fill: typeof import('~icons/mingcute/delete3-fill.jsx')['default']
  const IconMingcuteDownload2Fill: typeof import('~icons/mingcute/download2-fill.jsx')['default']
  const IconMingcuteEdit2Fill: typeof import('~icons/mingcute/edit2-fill.jsx')['default']
  const IconMingcuteExitFill: typeof import('~icons/mingcute/exit-fill.jsx')['default']
  const IconMingcuteEye2Fill: typeof import('~icons/mingcute/eye2-fill.jsx')['default']
  const IconMingcuteEyeCloseFill: typeof import('~icons/mingcute/eye-close-fill.jsx')['default']
  const IconMingcuteFileFill: typeof import('~icons/mingcute/file-fill.jsx')['default']
  const IconMingcuteFileUploadFill: typeof import('~icons/mingcute/file-upload-fill.jsx')['default']
  const IconMingcuteFullscreenExitFill: typeof import('~icons/mingcute/fullscreen-exit-fill.jsx')['default']
  const IconMingcuteFullscreenFill: typeof import('~icons/mingcute/fullscreen-fill.jsx')['default']
  const IconMingcuteGroup2Fill: typeof import('~icons/mingcute/group2-fill.jsx')['default']
  const IconMingcuteIdcardFill: typeof import('~icons/mingcute/idcard-fill.jsx')['default']
  const IconMingcuteInformationLine: typeof import('~icons/mingcute/information-line.jsx')['default']
  const IconMingcuteLoading3Fill: typeof import('~icons/mingcute/loading3-fill.jsx')['default']
  const IconMingcuteLookDownFill: typeof import('~icons/mingcute/look-down-fill.jsx')['default']
  const IconMingcuteMessage1Fill: typeof import('~icons/mingcute/message1-fill.jsx')['default']
  const IconMingcuteMinimizeFill: typeof import('~icons/mingcute/minimize-fill.jsx')['default']
  const IconMingcuteMore2Fill: typeof import('~icons/mingcute/more2-fill.jsx')['default']
  const IconMingcuteNotificationOffFill: typeof import('~icons/mingcute/notification-off-fill.jsx')['default']
  const IconMingcutePauseFill: typeof import('~icons/mingcute/pause-fill.jsx')['default']
  const IconMingcutePic2Fill: typeof import('~icons/mingcute/pic2-fill.jsx')['default']
  const IconMingcutePlayFill: typeof import('~icons/mingcute/play-fill.jsx')['default']
  const IconMingcuteSettings5Fill: typeof import('~icons/mingcute/settings5-fill.jsx')['default']
  const IconMingcuteTransfer3Fill: typeof import('~icons/mingcute/transfer3-fill.jsx')['default']
  const IconMingcuteVolumeFill: typeof import('~icons/mingcute/volume-fill.jsx')['default']
  const IconMingcuteVolumeMuteFill: typeof import('~icons/mingcute/volume-mute-fill.jsx')['default']
  const IconMingcuteWarningFill: typeof import('~icons/mingcute/warning-fill.jsx')['default']
  const IconSolarSledgehammerBold: typeof import('~icons/solar/sledgehammer-bold.jsx')['default']
}
