/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconLetsIconsSendHorFill: typeof import('~icons/lets-icons/send-hor-fill.jsx').default
  const IconMingcuteArrowLeftFill: typeof import('~icons/mingcute/arrow-left-fill.jsx').default
  const IconMingcuteArrowRightFill: typeof import('~icons/mingcute/arrow-right-fill.jsx').default
  const IconMingcuteCheckFill: typeof import('~icons/mingcute/check-fill.jsx').default
  const IconMingcuteCloseFill: typeof import('~icons/mingcute/close-fill.jsx').default
  const IconMingcuteCopy2Fill: typeof import('~icons/mingcute/copy2-fill.jsx').default
  const IconMingcuteCornerUpLeftFill: typeof import('~icons/mingcute/corner-up-left-fill.jsx').default
  const IconMingcuteCornerUpLeftLine: typeof import('~icons/mingcute/corner-up-left-line.jsx').default
  const IconMingcuteCornerUpRightLine: typeof import('~icons/mingcute/corner-up-right-line.jsx').default
  const IconMingcuteDownload2Fill: typeof import('~icons/mingcute/download2-fill.jsx').default
  const IconMingcuteEdit2Fill: typeof import('~icons/mingcute/edit2-fill.jsx').default
  const IconMingcuteEmoji2Fill: typeof import('~icons/mingcute/emoji2-fill.jsx').default
  const IconMingcuteFileFill: typeof import('~icons/mingcute/file-fill.jsx').default
  const IconMingcuteFullscreenExitFill: typeof import('~icons/mingcute/fullscreen-exit-fill.jsx').default
  const IconMingcuteFullscreenFill: typeof import('~icons/mingcute/fullscreen-fill.jsx').default
  const IconMingcuteLoading3Fill: typeof import('~icons/mingcute/loading3-fill.jsx').default
  const IconMingcuteLockFill: typeof import('~icons/mingcute/lock-fill.jsx').default
  const IconMingcuteMicFill: typeof import('~icons/mingcute/mic-fill.jsx').default
  const IconMingcuteNotificationOffFill: typeof import('~icons/mingcute/notification-off-fill.jsx').default
  const IconMingcutePauseFill: typeof import('~icons/mingcute/pause-fill.jsx').default
  const IconMingcutePhoneFill: typeof import('~icons/mingcute/phone-fill.jsx').default
  const IconMingcutePhotoAlbum2Fill: typeof import('~icons/mingcute/photo-album2-fill.jsx').default
  const IconMingcutePic2Fill: typeof import('~icons/mingcute/pic2-fill.jsx').default
  const IconMingcutePinFill: typeof import('~icons/mingcute/pin-fill.jsx').default
  const IconMingcutePlayFill: typeof import('~icons/mingcute/play-fill.jsx').default
  const IconMingcuteRefreshAnticlockwise1Line: typeof import('~icons/mingcute/refresh-anticlockwise1-line.jsx').default
  const IconMingcuteRightLine: typeof import('~icons/mingcute/right-line.jsx').default
  const IconMingcuteStarFill: typeof import('~icons/mingcute/star-fill.jsx').default
  const IconMingcuteTransfer3Fill: typeof import('~icons/mingcute/transfer3-fill.jsx').default
  const IconMingcuteUnlockFill: typeof import('~icons/mingcute/unlock-fill.jsx').default
  const IconMingcuteVolumeFill: typeof import('~icons/mingcute/volume-fill.jsx').default
  const IconMingcuteVolumeMuteFill: typeof import('~icons/mingcute/volume-mute-fill.jsx').default
  const IconMingcuteWarningFill: typeof import('~icons/mingcute/warning-fill.jsx').default
}
