/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconFa6SolidCrow: typeof import('~icons/fa6-solid/crow.jsx')['default']
  const IconFaSolidUserFriends: typeof import('~icons/fa-solid/user-friends.jsx')['default']
  const IconGravityUiCaretDown: (typeof import("~icons/gravity-ui/caret-down.jsx"))["default"]
  const IconGravityUiCheck: (typeof import("~icons/gravity-ui/check.jsx"))["default"]
  const IconGravityUiPlus: typeof import('~icons/gravity-ui/plus.jsx')['default']
  const IconIconParkSolidDownOne: (typeof import("~icons/icon-park-solid/down-one.jsx"))["default"]
<<<<<<< HEAD
=======
  const IconLetsIconsSendHorFill: typeof import('~icons/lets-icons/send-hor-fill.jsx')['default']
>>>>>>> master
  const IconLineMdAlert: (typeof import("~icons/line-md/alert.jsx"))["default"]
  const IconMaterialSymbolsErrorOutline: typeof import('~icons/material-symbols/error-outline.jsx')['default']
  const IconMaterialSymbolsInfoOutline: typeof import('~icons/material-symbols/info-outline.jsx')['default']
  const IconMaterialSymbolsSend: typeof import('~icons/material-symbols/send.jsx')['default']
  const IconMdiAbout: typeof import('~icons/mdi/about.jsx')['default']
  const IconMdiAccount: typeof import('~icons/mdi/account.jsx')['default']
  const IconMdiCamera: (typeof import("~icons/mdi/camera.jsx"))["default"]
  const IconMdiCheck: typeof import('~icons/mdi/check.jsx')['default']
  const IconMdiClose: typeof import('~icons/mdi/close.jsx')['default']
  const IconMdiDelete: typeof import('~icons/mdi/delete.jsx')['default']
  const IconMdiEdit: typeof import('~icons/mdi/edit.jsx')['default']
  const IconMdiHide: typeof import('~icons/mdi/hide.jsx')['default']
  const IconMdiIdentificationCard: typeof import('~icons/mdi/identification-card.jsx')['default']
  const IconMdiLogout: typeof import('~icons/mdi/logout.jsx')['default']
  const IconMdiMaximize: typeof import('~icons/mdi/maximize.jsx')['default']
  const IconMdiMessage: typeof import('~icons/mdi/message.jsx')['default']
  const IconMdiMinimize: typeof import('~icons/mdi/minimize.jsx')['default']
  const IconMdiMoreVert: typeof import('~icons/mdi/more-vert.jsx')['default']
  const IconMdiNotifications: typeof import('~icons/mdi/notifications.jsx')['default']
  const IconMdiNotificationsOff: typeof import('~icons/mdi/notifications-off.jsx')['default']
  const IconMdiServer: typeof import('~icons/mdi/server.jsx')['default']
  const IconMdiSettings: typeof import('~icons/mdi/settings.jsx')['default']
  const IconMdiShow: typeof import('~icons/mdi/show.jsx')['default']
  const IconMdiSpeakerphone: typeof import('~icons/mdi/speakerphone.jsx')['default']
  const IconMdiTheme: typeof import('~icons/mdi/theme.jsx')['default']
  const IconMingcuteCheckFill: typeof import('~icons/mingcute/check-fill.jsx')['default']
  const IconMingcuteDownFill: typeof import('~icons/mingcute/down-fill.jsx')['default']
  const IconSvgSpinners3DotsFade: typeof import('~icons/svg-spinners/3-dots-fade.jsx')['default']
}
