[package]
name = "huginn"
version = "0.15.0"
description = "Huginn's desktop application"
authors = ["Matin"]
repository = ""
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
[build-dependencies.tauri-build]
version = "2.0.1"
features = []

[dependencies]
serde_json = "1.0"
tauri-plugin-shell = "2.0.1"
tauri-plugin-process = "2.0.1"
tauri-plugin-fs = "2.0.1"
tokio = "1.40.0"
tauri-plugin-deep-link = "2"
tauri-plugin-notification = "2"
tauri-winrt-notification = "0.7.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0"
features = ["protocol-asset", "devtools", "tray-icon"]

[target]
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))"]
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.2"

[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies.tauri-plugin-single-instance]
version = "2.0.0"
features = ["deep-link"]

[profile]
[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
