[package]
name = "huginn"
version = "0.3.4-nightly.4"
description = "Huginn's desktop application"
authors = [ "Matin" ]
repository = ""
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = [ "lib", "cdylib", "staticlib" ]

[build-dependencies]
[build-dependencies.tauri-build]
version = "2.0.0-rc"
features = []

[dependencies]
serde_json = "1.0"
tauri-plugin-shell = "2.0.0-rc"
tauri-plugin-process = "2.0.0-rc"
tauri-plugin-fs = "2.0.0-rc"
tokio = "1.40.0"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.tauri]
version = "2.0.0-rc"
features = [ "devtools" ]

[target]
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))"]
[target."cfg(not(any(target_os = \"android\", target_os = \"ios\")))".dependencies]
tauri-plugin-updater = "2.0.0-rc"
