/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutAuthImport } from './routes/_layoutAuth'
import { Route as ChannelChannelIdImport } from './routes/channel.$channelId'
import { Route as LayoutAuthLoginImport } from './routes/_layoutAuth/login'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_layoutAuth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ChannelChannelIdRoute = ChannelChannelIdImport.update({
  path: '/channel/$channelId',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthLoginRoute = LayoutAuthLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutAuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layoutAuth': {
      id: '/_layoutAuth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof rootRoute
    }
    '/_layoutAuth/login': {
      id: '/_layoutAuth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutAuthLoginImport
      parentRoute: typeof LayoutAuthImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  LayoutAuthRoute: LayoutAuthRoute.addChildren({ LayoutAuthLoginRoute }),
  ChannelChannelIdRoute,
})

/* prettier-ignore-end */
