/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as AppMainRouteImport } from "./routes/_app/_main";
import { Route as AppMainHomeRouteImport } from "./routes/_app/_main/_home";
import { Route as AppMainHomeChannelsAtmeChannelIdRouteImport } from "./routes/_app/_main/_home/channels.@me.$channelId";
import { Route as AppMainHomeChannelsAtmeIndexRouteImport } from "./routes/_app/_main/_home/channels.@me.index";
import { Route as AppMainHomeFriendsRouteImport } from "./routes/_app/_main/_home/friends";
import { Route as AppStartRouteImport } from "./routes/_app/_start";
import { Route as AppStartIndexRouteImport } from "./routes/_app/_start/index";
import { Route as AppStartLoginRouteImport } from "./routes/_app/_start/login";
import { Route as AppStartOauthRedirectRouteImport } from "./routes/_app/_start/oauth-redirect";
import { Route as AppStartRegisterRouteImport } from "./routes/_app/_start/register";
import { Route as VoiceDebugRouteImport } from "./routes/voice-debug";

const VoiceDebugRoute = VoiceDebugRouteImport.update({
   id: "/voice-debug",
   path: "/voice-debug",
   getParentRoute: () => rootRouteImport,
} as any);
const AppRoute = AppRouteImport.update({
   id: "/_app",
   getParentRoute: () => rootRouteImport,
} as any);
const AppStartRoute = AppStartRouteImport.update({
   id: "/_start",
   getParentRoute: () => AppRoute,
} as any);
const AppMainRoute = AppMainRouteImport.update({
   id: "/_main",
   getParentRoute: () => AppRoute,
} as any);
const AppStartIndexRoute = AppStartIndexRouteImport.update({
   id: "/",
   path: "/",
   getParentRoute: () => AppStartRoute,
} as any);
const AppStartRegisterRoute = AppStartRegisterRouteImport.update({
   id: "/register",
   path: "/register",
   getParentRoute: () => AppStartRoute,
} as any);
const AppStartOauthRedirectRoute = AppStartOauthRedirectRouteImport.update({
   id: "/oauth-redirect",
   path: "/oauth-redirect",
   getParentRoute: () => AppStartRoute,
} as any);
const AppStartLoginRoute = AppStartLoginRouteImport.update({
   id: "/login",
   path: "/login",
   getParentRoute: () => AppStartRoute,
} as any);
const AppMainHomeRoute = AppMainHomeRouteImport.update({
   id: "/_home",
   getParentRoute: () => AppMainRoute,
} as any);
const AppMainHomeFriendsRoute = AppMainHomeFriendsRouteImport.update({
   id: "/friends",
   path: "/friends",
   getParentRoute: () => AppMainHomeRoute,
} as any);
const AppMainHomeChannelsAtmeIndexRoute = AppMainHomeChannelsAtmeIndexRouteImport.update({
   id: "/channels/@me/",
   path: "/channels/@me/",
   getParentRoute: () => AppMainHomeRoute,
} as any);
const AppMainHomeChannelsAtmeChannelIdRoute = AppMainHomeChannelsAtmeChannelIdRouteImport.update({
   id: "/channels/@me/$channelId",
   path: "/channels/@me/$channelId",
   getParentRoute: () => AppMainHomeRoute,
} as any);

export interface FileRoutesByFullPath {
   "/": typeof AppStartIndexRoute;
   "/voice-debug": typeof VoiceDebugRoute;
   "/login": typeof AppStartLoginRoute;
   "/oauth-redirect": typeof AppStartOauthRedirectRoute;
   "/register": typeof AppStartRegisterRoute;
   "/friends": typeof AppMainHomeFriendsRoute;
   "/channels/@me/$channelId": typeof AppMainHomeChannelsAtmeChannelIdRoute;
   "/channels/@me/": typeof AppMainHomeChannelsAtmeIndexRoute;
}
export interface FileRoutesByTo {
   "/": typeof AppStartIndexRoute;
   "/voice-debug": typeof VoiceDebugRoute;
   "/login": typeof AppStartLoginRoute;
   "/oauth-redirect": typeof AppStartOauthRedirectRoute;
   "/register": typeof AppStartRegisterRoute;
   "/friends": typeof AppMainHomeFriendsRoute;
   "/channels/@me/$channelId": typeof AppMainHomeChannelsAtmeChannelIdRoute;
   "/channels/@me": typeof AppMainHomeChannelsAtmeIndexRoute;
}
export interface FileRoutesById {
   __root__: typeof rootRouteImport;
   "/_app": typeof AppRouteWithChildren;
   "/voice-debug": typeof VoiceDebugRoute;
   "/_app/_main": typeof AppMainRouteWithChildren;
   "/_app/_start": typeof AppStartRouteWithChildren;
   "/_app/_main/_home": typeof AppMainHomeRouteWithChildren;
   "/_app/_start/login": typeof AppStartLoginRoute;
   "/_app/_start/oauth-redirect": typeof AppStartOauthRedirectRoute;
   "/_app/_start/register": typeof AppStartRegisterRoute;
   "/_app/_start/": typeof AppStartIndexRoute;
   "/_app/_main/_home/friends": typeof AppMainHomeFriendsRoute;
   "/_app/_main/_home/channels/@me/$channelId": typeof AppMainHomeChannelsAtmeChannelIdRoute;
   "/_app/_main/_home/channels/@me/": typeof AppMainHomeChannelsAtmeIndexRoute;
}
export interface FileRouteTypes {
   fileRoutesByFullPath: FileRoutesByFullPath;
   fullPaths: "/" | "/voice-debug" | "/login" | "/oauth-redirect" | "/register" | "/friends" | "/channels/@me/$channelId" | "/channels/@me/";
   fileRoutesByTo: FileRoutesByTo;
   to: "/" | "/voice-debug" | "/login" | "/oauth-redirect" | "/register" | "/friends" | "/channels/@me/$channelId" | "/channels/@me";
   id:
      | "__root__"
      | "/_app"
      | "/voice-debug"
      | "/_app/_main"
      | "/_app/_start"
      | "/_app/_main/_home"
      | "/_app/_start/login"
      | "/_app/_start/oauth-redirect"
      | "/_app/_start/register"
      | "/_app/_start/"
      | "/_app/_main/_home/friends"
      | "/_app/_main/_home/channels/@me/$channelId"
      | "/_app/_main/_home/channels/@me/";
   fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
   AppRoute: typeof AppRouteWithChildren;
   VoiceDebugRoute: typeof VoiceDebugRoute;
}

declare module "@tanstack/react-router" {
   interface FileRoutesByPath {
      "/voice-debug": {
         id: "/voice-debug";
         path: "/voice-debug";
         fullPath: "/voice-debug";
         preLoaderRoute: typeof VoiceDebugRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/_app": {
         id: "/_app";
         path: "";
         fullPath: "/";
         preLoaderRoute: typeof AppRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/_app/_start": {
         id: "/_app/_start";
         path: "";
         fullPath: "/";
         preLoaderRoute: typeof AppStartRouteImport;
         parentRoute: typeof AppRoute;
      };
      "/_app/_main": {
         id: "/_app/_main";
         path: "";
         fullPath: "/";
         preLoaderRoute: typeof AppMainRouteImport;
         parentRoute: typeof AppRoute;
      };
      "/_app/_start/": {
         id: "/_app/_start/";
         path: "/";
         fullPath: "/";
         preLoaderRoute: typeof AppStartIndexRouteImport;
         parentRoute: typeof AppStartRoute;
      };
      "/_app/_start/register": {
         id: "/_app/_start/register";
         path: "/register";
         fullPath: "/register";
         preLoaderRoute: typeof AppStartRegisterRouteImport;
         parentRoute: typeof AppStartRoute;
      };
      "/_app/_start/oauth-redirect": {
         id: "/_app/_start/oauth-redirect";
         path: "/oauth-redirect";
         fullPath: "/oauth-redirect";
         preLoaderRoute: typeof AppStartOauthRedirectRouteImport;
         parentRoute: typeof AppStartRoute;
      };
      "/_app/_start/login": {
         id: "/_app/_start/login";
         path: "/login";
         fullPath: "/login";
         preLoaderRoute: typeof AppStartLoginRouteImport;
         parentRoute: typeof AppStartRoute;
      };
      "/_app/_main/_home": {
         id: "/_app/_main/_home";
         path: "";
         fullPath: "/";
         preLoaderRoute: typeof AppMainHomeRouteImport;
         parentRoute: typeof AppMainRoute;
      };
      "/_app/_main/_home/friends": {
         id: "/_app/_main/_home/friends";
         path: "/friends";
         fullPath: "/friends";
         preLoaderRoute: typeof AppMainHomeFriendsRouteImport;
         parentRoute: typeof AppMainHomeRoute;
      };
      "/_app/_main/_home/channels/@me/": {
         id: "/_app/_main/_home/channels/@me/";
         path: "/channels/@me";
         fullPath: "/channels/@me/";
         preLoaderRoute: typeof AppMainHomeChannelsAtmeIndexRouteImport;
         parentRoute: typeof AppMainHomeRoute;
      };
      "/_app/_main/_home/channels/@me/$channelId": {
         id: "/_app/_main/_home/channels/@me/$channelId";
         path: "/channels/@me/$channelId";
         fullPath: "/channels/@me/$channelId";
         preLoaderRoute: typeof AppMainHomeChannelsAtmeChannelIdRouteImport;
         parentRoute: typeof AppMainHomeRoute;
      };
   }
}

interface AppMainHomeRouteChildren {
   AppMainHomeFriendsRoute: typeof AppMainHomeFriendsRoute;
   AppMainHomeChannelsAtmeChannelIdRoute: typeof AppMainHomeChannelsAtmeChannelIdRoute;
   AppMainHomeChannelsAtmeIndexRoute: typeof AppMainHomeChannelsAtmeIndexRoute;
}

const AppMainHomeRouteChildren: AppMainHomeRouteChildren = {
   AppMainHomeFriendsRoute: AppMainHomeFriendsRoute,
   AppMainHomeChannelsAtmeChannelIdRoute: AppMainHomeChannelsAtmeChannelIdRoute,
   AppMainHomeChannelsAtmeIndexRoute: AppMainHomeChannelsAtmeIndexRoute,
};

const AppMainHomeRouteWithChildren = AppMainHomeRoute._addFileChildren(AppMainHomeRouteChildren);

interface AppMainRouteChildren {
   AppMainHomeRoute: typeof AppMainHomeRouteWithChildren;
}

const AppMainRouteChildren: AppMainRouteChildren = {
   AppMainHomeRoute: AppMainHomeRouteWithChildren,
};

const AppMainRouteWithChildren = AppMainRoute._addFileChildren(AppMainRouteChildren);

interface AppStartRouteChildren {
   AppStartLoginRoute: typeof AppStartLoginRoute;
   AppStartOauthRedirectRoute: typeof AppStartOauthRedirectRoute;
   AppStartRegisterRoute: typeof AppStartRegisterRoute;
   AppStartIndexRoute: typeof AppStartIndexRoute;
}

const AppStartRouteChildren: AppStartRouteChildren = {
   AppStartLoginRoute: AppStartLoginRoute,
   AppStartOauthRedirectRoute: AppStartOauthRedirectRoute,
   AppStartRegisterRoute: AppStartRegisterRoute,
   AppStartIndexRoute: AppStartIndexRoute,
};

const AppStartRouteWithChildren = AppStartRoute._addFileChildren(AppStartRouteChildren);

interface AppRouteChildren {
   AppMainRoute: typeof AppMainRouteWithChildren;
   AppStartRoute: typeof AppStartRouteWithChildren;
}

const AppRouteChildren: AppRouteChildren = {
   AppMainRoute: AppMainRouteWithChildren,
   AppStartRoute: AppStartRouteWithChildren,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren: RootRouteChildren = {
   AppRoute: AppRouteWithChildren,
   VoiceDebugRoute: VoiceDebugRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
