/**
 * Emoji Sprite Sheet Generator
 *
 * Usage:
 *   node generate-sprite.mjs --input ./emoji-pngs --output ./public --size 32 --cols 42
 *
 * Inputs:  a flat directory of PNG files named by emoji codepoint, e.g. 1f600.png
 * Outputs:
 *   public/emoji-sheet.png   — the sprite sheet
 *   public/emoji-sheet.webp  — WebP version (~40% smaller)
 *   public/emoji-map.json    — position map: { "1f600": { x, y, row, col } }
 *   public/emoji.css         — ready-to-use CSS classes
 */

import fs from "fs";
import path from "path";
import sharp from "sharp";
import { parseArgs } from "util";

// ─── CLI args ────────────────────────────────────────────────────────────────

const { values: args } = parseArgs({
   options: {
      input: { type: "string", default: "./pngs" },
      output: { type: "string", default: "./out" },
      size: { type: "string", default: "64" }, // px per emoji cell
      cols: { type: "string", default: "42" }, // emojis per row
      padding: { type: "string", default: "0" }, // px gap (prevents bleed)
   },
});

const CELL = parseInt(args.size, 10);
const COLS = parseInt(args.cols, 10);
const PAD = parseInt(args.padding, 10);
const STEP = CELL + PAD * 2; // total cell stride including padding
const INPUT = path.resolve(args.input);
const OUTPUT = path.resolve(args.output);

fs.mkdirSync(OUTPUT, { recursive: true });

// ─── Collect emoji files ─────────────────────────────────────────────────────

const files = fs
   .readdirSync(INPUT)
   .filter((f) => f.endsWith(".png"))
   .sort(); // stable order → deterministic sheet

if (files.length === 0) {
   console.error(`No PNG files found in ${INPUT}`);
   process.exit(1);
}

console.log(`Found ${files.length} emojis — cell ${CELL}px, ${COLS} cols, ${PAD}px padding`);

// ─── Calculate canvas dimensions ─────────────────────────────────────────────

const ROWS = Math.ceil(files.length / COLS);
const SHEET_WIDTH = COLS * STEP;
const SHEET_HEIGHT = ROWS * STEP;

console.log(`Sheet size: ${SHEET_WIDTH}×${SHEET_HEIGHT}px  (${ROWS} rows)`);

// ─── Build compositing list ───────────────────────────────────────────────────

const positionMap = {}; // codepoint → { x, y, row, col }
const composites = []; // sharp composite input list

for (let i = 0; i < files.length; i++) {
   const file = files[i];
   const codepoint = path.basename(file, ".png").toLowerCase();
   const col = i % COLS;
   const row = Math.floor(i / COLS);
   const x = col * STEP + PAD;
   const y = row * STEP + PAD;

   positionMap[codepoint] = { x, y, row, col };

   composites.push({
      input: await sharp(path.join(INPUT, file))
         .resize(CELL, CELL, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
         .toBuffer(),
      left: x,
      top: y,
   });
}

// ─── Render PNG sheet ─────────────────────────────────────────────────────────

console.log("Rendering PNG sprite sheet…");

const baseImage = sharp({
   create: {
      width: SHEET_WIDTH,
      height: SHEET_HEIGHT,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
   },
});

const pngPath = path.join(OUTPUT, "emoji-sheet.png");
await baseImage.composite(composites).png({ compressionLevel: 9 }).toFile(pngPath);

const pngSize = (fs.statSync(pngPath).size / 1024).toFixed(1);
console.log(`✓ emoji-sheet.png  (${pngSize} KB)`);

// ─── Render WebP sheet ────────────────────────────────────────────────────────

// console.log("Rendering WebP sprite sheet…");

// const webpPath = path.join(OUTPUT, "emoji-sheet.webp");
// await sharp(pngPath).webp({ quality: 90, lossless: false }).toFile(webpPath);

// const webpSize = (fs.statSync(webpPath).size / 1024).toFixed(1);
// console.log(`✓ emoji-sheet.webp (${webpSize} KB)`);

// ─── Write position map JSON ──────────────────────────────────────────────────

const mapPath = path.join(OUTPUT, "emoji-map.json");
fs.writeFileSync(
   mapPath,
   JSON.stringify(
      {
         meta: {
            cellSize: CELL,
            padding: PAD,
            step: STEP,
            cols: COLS,
            rows: ROWS,
            sheetWidth: SHEET_WIDTH,
            sheetHeight: SHEET_HEIGHT,
            count: files.length,
         },
         emojis: positionMap,
      },
      null,
      2,
   ),
);
console.log(`✓ emoji-map.json`);

// ─── Write CSS ────────────────────────────────────────────────────────────────

// Percentage-based positions so the same CSS works at any rendered size.
// background-size is always 100% × (COLS/ROWS) ratio.
// const cssLines = [
//    `/* Auto-generated by generate-sprite.mjs — do not edit */`,
//    `.emoji {`,
//    `  display: inline-block;`,
//    `  width:  ${CELL}px;`,
//    `  height: ${CELL}px;`,
//    `  background-image: url('emoji-sheet.webp'), url('emoji-sheet.png');`,
//    `  background-repeat: no-repeat;`,
//    `  background-size: ${COLS * 100}% ${ROWS * 100}%;`,
//    `}`,
//    ``,
// ];

// for (const [cp, { col, row }] of Object.entries(positionMap)) {
//    // background-position: X% Y%
//    // 0% = left/top edge, 100% = right/bottom edge
//    const xPct = COLS === 1 ? 0 : ((col / (COLS - 1)) * 100).toFixed(4);
//    const yPct = ROWS === 1 ? 0 : ((row / (ROWS - 1)) * 100).toFixed(4);
//    cssLines.push(`.emoji-${cp} { background-position: ${xPct}% ${yPct}%; }`);
// }

// const cssPath = path.join(OUTPUT, "emoji.css");
// fs.writeFileSync(cssPath, cssLines.join("\n"));
// console.log(`✓ emoji.css  (${cssLines.length} rules)`);

// ─── Done ─────────────────────────────────────────────────────────────────────

console.log(`\nDone! All files written to ${OUTPUT}`);
console.log(`\nQuick usage in HTML:`);
console.log(`  <link rel="stylesheet" href="emoji.css">`);
console.log(`  <span class="emoji emoji-1f600" title="😀"></span>`);
