name: release-please

permissions:
  contents: write
  pull-requests: write

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
