name: release
permissions:
   contents: write
   pull-requests: write
on:
   workflow_dispatch:
      inputs:
         force_app_release:
            description: "Force app release even if no changes detected"
            required: false
            type: boolean
            default: true

         app_version:
            description: "Override app version"
            required: false
            type: string

   push:
      branches:
         - master
         - release
jobs:
   release-please:
      runs-on: ubuntu-latest
      outputs:
         app_release_created: ${{ inputs.force_app_release || steps.release.outputs['packages/huginn-app--release_created'] || 'false' }}
         app_version: ${{ inputs.app_version || steps.release.outputs['packages/huginn-app--version'] || 'unknown' }}

      steps:
         - uses: actions/checkout@v4

         - name: run release-please on release commit or dispatch
           id: release
           uses: googleapis/release-please-action@v4
           with:
              target-branch: ${{ github.ref_name }}
           if: |
              github.event_name == 'workflow_dispatch' ||
              contains(github.event.head_commit.message, ': release')

         - name: Compute outputs
           id: outputs
           run: |
              if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ inputs.app_version }}" ]]; then
                 echo "app_release_created=${{ inputs.force_app_release }}" >> "$GITHUB_OUTPUT"
                 echo "app_version=${{ inputs.app_version }}" >> "$GITHUB_OUTPUT"
              else
                 echo "app_release_created=${{ steps.release.outputs['packages/huginn-app--release_created'] || 'false' }}" >> "$GITHUB_OUTPUT"
                 echo "app_version=${{ steps.release.outputs['packages/huginn-app--version'] || 'unknown' }}" >> "$GITHUB_OUTPUT"
              fi
   publish-app:
      needs: release-please
      strategy:
         fail-fast: false
         matrix:
            include:
               - platform: "windows-latest"
                 args: ""
      runs-on: ${{ matrix.platform }}
      if: ${{needs.release-please.outputs.app_release_created == 'true'}}
      env:
         VITE_PUBLIC_POSTHOG_KEY: ${{secrets.VITE_PUBLIC_POSTHOG_KEY}}
         VITE_PUBLIC_CLOUDFLARE_TURN_ID: ${{secrets.VITE_PUBLIC_CLOUDFLARE_TURN_ID}}
         VITE_PUBLIC_CLOUDFLARE_TURN_TOKEN: ${{secrets.VITE_PUBLIC_CLOUDFLARE_TURN_TOKEN}}
         VITE_PUBLIC_OAUTH_REDIRECT: ${{secrets.VITE_PUBLIC_OAUTH_REDIRECT}}
         POSTHOG_CLI_API_KEY: ${{secrets.POSTHOG_CLI_API_KEY}}
         POSTHOG_PROJECT_ID: ${{secrets.POSTHOG_PROJECT_ID}}
         CI: ${{github.env.CI}}
      steps:
         - uses: actions/checkout@v4

         - name: install pnpm
           uses: pnpm/action-setup@v4
         - name: install Bun
           uses: oven-sh/setup-bun@v2
           with:
              bun-version: latest

         - name: install frontend dependencies
           run: cd packages/huginn-app && pnpm install --ignore-scripts --filter huginn-app-react --filter @huginn/api --filter @huginn/shared

         - name: setup cmake
           uses: jwlawson/actions-setup-cmake@v2
           with:
              cmake-version: "4.x.x"

         - name: compile native-addon
           run: cd packages/native-addon && pnpm install && pnpm run build

         - name: build app
           run: cd packages/huginn-app && pnpm run build

         # - name: Inject & upload source maps to PostHog
         #   uses: PostHog/upload-source-maps@v2.0.0
         #   with:
         #      directory: packages/huginn-app/dist
         #      project-id: ${{ secrets.POSTHOG_PROJECT_ID }}
         #      api-key: ${{ secrets.POSTHOG_CLI_API_KEY }}
         #      host: https://eu.posthog.com
         #      release-name: huginn-app
         #      release-version: ${{ needs.release-please.outputs.app_version}}

         - name: publish app
           env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           run: cd packages/huginn-app && bun run scripts/upload.ts
