name: release

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run release-please on release commit or dispatch
        uses: googleapis/release-please-action@v4
        id: release
        if: |
          github.event.head_commit.message == 'workflow_dispatch' ||
          contains(env.commit_message, ': release')
